INSERT INTO ref_meta (key, value) VALUES
    ('schema_version', '1'),
    ('bundle_version', '2026.08.30-dev'),
    ('generated_at',   '2026-08-30'),
    ('project',        'Hammy'),
    ('project_url',    'https://hammybot.org');

INSERT INTO ref_sources (dataset, source_name, source_url, license, retrieved, notes) VALUES
    ('band_segments', 'FCC Part 97 Subpart D', 'https://www.ecfr.gov/current/title-47/part-97',
     'US Government work, public domain', NULL,
     'HAND-ENTERED STARTER DATA. Must be verified against the current Part 97 text before shipping. Wrong band edges can put an operator out of band.'),

    ('band_segments_iaru', 'IARU Region 1/2/3 band plans', 'https://www.iaru.org/', 'See IARU', NULL,
     'Only allocation extents are seeded, not the full mode/bandwidth plans. Incomplete.'),

    ('dxcc_entities', 'ARRL DXCC list / cty.dat', 'https://www.country-files.com/',
     'Free for amateur radio use, see country-files.com', NULL,
     'DEMO SUBSET ONLY - about 25 entities to exercise the schema. Real bundle must be generated by parsing cty.dat.'),

    ('qcodes', 'ITU Q-code series', NULL, 'Public domain', NULL,
     'Amateur-relevant subset of the QRA-QUZ series.'),

    ('phonetics', 'ITU/NATO phonetic alphabet', NULL, 'Public domain', NULL, NULL),

    ('morse', 'ITU-R M.1677-1', NULL, 'Public domain', NULL,
     'International Morse. Does not include non-Latin extensions.'),

    ('coax_types', 'Manufacturer datasheets', NULL, 'Various', NULL,
     'Impedance, velocity factor and capacitance are nominal published figures. loss_k1/loss_k2 are deliberately NULL - populate from the actual datasheet for each cable rather than a generic approximation, since loss is what the calculator returns.'),

    ('ncdxf_beacons', 'NCDXF/IARU International Beacon Project', 'https://www.ncdxf.org/beacon/',
     'See NCDXF', NULL,
     'Station order is stable; individual beacons go offline for extended periods. The active flag needs refreshing against the NCDXF status page at build time.');
