-- Generated by audit.py --indexes. Runs last in the build.
-- The bundle is read-only, so indexes cost file size and nothing else.

-- candidate-prefix equality lookup; leading PK column, but stated explicitly because everything depends on it
CREATE INDEX IF NOT EXISTS idx_dxcc_prefixes_prefix ON "dxcc_prefixes" ("prefix");
-- joins back to dxcc_entities
CREATE INDEX IF NOT EXISTS idx_dxcc_prefixes_entity_id ON "dxcc_prefixes" ("entity_id");





ANALYZE;
